### ISSUE TITLE
Bronnen

### ISSUE THREAD

**Issue by ju5tu5** [fdnd-task/choices-choices-the-tech-stack#2]
https://www.softermii.com/blog/10-tips-in-choosing-the-best-tech-stack-for-your-web-application

https://symfony.com/ten-criteria

https://www.velvetech.com/blog/choosing-project-tech-stack-basic-principles/

https://tray.io/blog/align-revenue-ops-tech-stack

**Comment by KoopReynders** [comment]
Verplaatst naar de deeltaak
